export const ROOT_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const HOME_ROUTE = '/home'
export const CHAT_ROUTE = '/chat'
export const CHAT_ROOM_ROUTE = '/chat/:contactId'
export const ADD_CASE_STEP_ZERO_ROUTE = '/add-case-step-zero'
export const ADD_POST_ROUTE = '/add-post'
